### ISSUE TITLE
function not working

### ISSUE THREAD

**Issue by doledangkhoa** [ErickSilva2605/xamarinforms-pokedex#1]
The filter function ( types, weaknesses, ...) is not working sir.

**Comment by ErickSilva2605** [comment]
Sorry for the delay in responding.
I did not find a performative way to implement these filters using the PokéAPI, it does not provide these types of filters, I would need to obtain the entire list of pokemons to carry out the filters, mainly for weaknesses. And as it is a project just for study purposes, I just coded the interface of these filters.

Thanks for the contact!
